unpleasant = ['lousy','disappointed','discouraged','ashamed','powerless','diminished','guilty','dissatisfied',
        'miserable','detestable','repugnant','despicable','disgusting','abominable','terrible','in despair',
        'sulky','bad','upset','doubtful','uncertain','indecisive','perplexed','embarassed','hesitant',
        'shy','stupefied','disillusioned','unbelieving','skeptical','distrustful','misgiving','lost',
        'unsure','uneasy','pessimistic','tense''incapable','alone','paralyzed','fatigued','useless',
        'inferior','vulnerable','empty','forced','hesitant','despair','frustrated','distressed','woeful',
        'pathetic','tragic','in a stew','dominated','irritated','enraged','hostile','insulting',
        'annoyed','upset','hateful','offensive','bitter','aggresive','resentful','inflamed','provoked',
        'incensed','infuriated','cross','worked up','boiling','fuming','fearful','terrified','suspicious',
        'anxious','alarmed','panic','nervous','scared','worried','frightened','timid','shaky','restless',
        'doubtful','threatened','cowardly','quaking','wary','crushed','tormented','deprived','pained',
        'tortured','dejected','rejected','injured','offended','afflicted','aching','victimized',
        'heartbroken','agonized','appalled','humiliated','wronged','alienated','tearful','sorrowful',
        'pained','grief','anguish','desolate','desperate','pessimistic','unhappy','lonely','grieved',
        'mournful','dismayed','insensitive','dull','nonchalant','neutral','reserved','weary','bored',
        'preoccupied','cold','disinterested','lifeless'];

# unpleasant = {
#     'depressed': [
#         'lousy',
#         'disappointed',
#         'discouraged',
#         'ashamed',
#         'powerless',
#         'diminished',
#         'guilty',
#         'dissatisfied',
#         'miserable',
#         'detestable',
#         'repugnant',
#         'despicable',
#         'disgusting',
#         'abominable',
#         'terrible',
#         'in despair',
#         'sulky',
#         'bad'
#     ],
#     'confused': [
#         'upset',
#         'doubtful',
#         'uncertain',
#         'indecisive',
#         'perplexed',
#         'embarassed',
#         'hesitant',
#         'shy',
#         'stupefied',
#         'disillusioned',
#         'unbelieving',
#         'skeptical',
#         'distrustful',
#         'misgiving',
#         'lost',
#         'unsure',
#         'uneasy',
#         'pessimistic',
#         'tense'
#     ],
#     'helpless': [
#         'incapable',
#         'alone',
#         'paralyzed',
#         'fatigued',
#         'useless',
#         'inferior',
#         'vulnerable',
#         'empty',
#         'forced',
#         'hesitant',
#         'despair',
#         'frustrated',
#         'distressed',
#         'woeful',
#         'pathetic',
#         'tragic',
#         'in a stew',
#         'dominated'
#     ],
#     'angry': [
#         'irritated',
#         'enraged',
#         'hostile',
#         'insulting',
#         'annoyed',
#         'upset',
#         'hateful',
#         'offensive',
#         'bitter',
#         'aggresive',
#         'resentful',
#         'inflamed',
#         'provoked',
#         'incensed',
#         'infuriated',
#         'cross',
#         'worked up',
#         'boiling',
#         'fuming'
#     ],
#     'afraid': [
#         'fearful',
#         'terrified',
#         'suspicious',
#         'anxious',
#         'alarmed',
#         'panic',
#         'nervous',
#         'scared',
#         'worried',
#         'frightened',
#         'timid',
#         'shaky',
#         'restless',
#         'doubtful',
#         'threatened',
#         'cowardly',
#         'quaking',
#         'wary'
#     ],
#     'hurt': [
#         'crushed',
#         'tormented',
#         'deprived',
#         'pained',
#         'tortured',
#         'dejected',
#         'rejected',
#         'injured',
#         'offended',
#         'afflicted',
#         'aching',
#         'victimized',
#         'heartbroken',
#         'agonized',
#         'appalled',
#         'humiliated',
#         'wronged',
#         'alienated'
#     ],
#     'sad': [
#         'tearful',
#         'sorrowful',
#         'pained',
#         'grief',
#         'anguish',
#         'desolate',
#         'desperate',
#         'pessimistic',
#         'unhappy',
#         'lonely',
#         'grieved',
#         'mournful',
#         'dismayed'
#     ],
#     'indifferente': [
#         'insensitive',
#         'dull',
#         'nonchalant',
#         'neutral',
#         'reserved',
#         'weary',
#         'bored',
#         'preoccupied',
#         'cold',
#         'disinterested',
#         'lifeless'
#     ]
# }